
import { grocery } from "./app/shared/models/grocery";

export const sample_grocery: grocery[]=[
   {
    id:'1',
    name:'Cheese Buttons',
    price:590,
    favourite:false,
    stars:3.0,
    imageUrl:'assets/cheese button1.jpg',
    tags:['imported item'],
   },

   {
    id:'2',
    name:'Butter Carol Cookies',
    price:380,
    favourite:false,
    stars:3.0,
    imageUrl:'assets/cheesebutton.jpg',
    tags:['imported item'],
   },
   {
      id:'3',
      name:'Hawain Cookies',
      price:200,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'4',
      name:'Ginger Bisutes',
      price:120,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'5',
      name:'Milk Short Cake Bisuits',
      price:200,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'6',
      name:'Custard Cream Biscuits',
      price:120,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'7',
      name:'Snack Crackers',
      price:590,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'8',
      name:'Tikiri marie Bisuits',
      price:360,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'9',
      name:'Super Cream Cracker',
      price:380,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'10',
      name:'Onion Bisuits',
      price:280,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'11',
      name:'Gold Marie',
      price:350,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'12',
      name:'Nice Bisuits',
      price:450,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'13',
      name:'Cheese Cutz',
      price:590,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'14',
      name:'Chocolate Cream Bisuits',
      price:490,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
     {
      id:'15',
      name:'Chocolata Cream Bisuits',
      price:590,
      favourite:false,
      stars:3.0,
      imageUrl:'assets/cheesebutton.jpg',
      tags:['imported item'],
     },
]